### PR TITLE
Fix typo in src/Relations.php

### PR DESCRIPTION
**Pull request by pgrimaud**
Hello,

This PR will fix : 

- 1 typo in `src/Relations.php`

Cheers! :robot:

### CODE REVIEW

**Comment by Crell** [comment]
Hm.  That file is auto-generated off of the XML file, which is itself downloaded from upstream.  Looking at it, the typo exists upstream on the iana.org website: https://www.iana.org/assignments/link-relations/link-relations.xml  (It's toward the bottom.)

Any changes here would get overwritten the next time we regenerate it; really, it would be better to bug IANA to fix their typo instead.  I... have no idea what the process is for that.

**Comment by pgrimaud** [comment]
Hi @Crell 

I dropped an email to iana.org website. So the typo on this repository will be fixed automatically in the future. 😄

**Comment by pgrimaud** [comment]
IANA fixed the typo. Next time you will regenerate files, it will be perfect. 👌 

Cheers

**Comment by Crell** [comment]
The Internet thanks you!  Regeneration PR here: #9.

**Pull request closed without merging**
